# Generated by Django 5.2.17 on 2026-08-21 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal/admin title for identifying the question.', max_length=200)),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('interview', 'Interview')], max_length=20)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('gap_fill', 'Gap Fill'), ('ordering', 'Ordering'), ('long_text', 'Long Written Response'), ('recorded_response', 'Recorded Response'), ('read_aloud', 'Read Aloud'), ('interview_response', 'Interview Response')], max_length=30)),
                ('prompt_text', models.TextField(blank=True, help_text='The actual question or instruction.')),
                ('prompt_audio', models.FileField(blank=True, null=True, upload_to='question_bank/question_audio/')),
                ('prompt_image', models.FileField(blank=True, null=True, upload_to='question_bank/question_images/')),
                ('show_prompt_text', models.BooleanField(default=True, help_text='Disable this when the question should be heard but not displayed to the student.')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('default_points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('automatic_marking', models.BooleanField(default=False)),
                ('ai_grading_required', models.BooleanField(default=False)),
                ('manual_review_allowed', models.BooleanField(default=True)),
                ('preparation_seconds', models.PositiveIntegerField(blank=True, help_text='Optional override of the Test Part preparation timer.', null=True)),
                ('response_seconds', models.PositiveIntegerField(blank=True, help_text='Optional override of the Test Part response timer.', null=True)),
                ('min_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('max_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, help_text='Optional answer explanation visible after grading.')),
                ('evaluator_notes', models.TextField(blank=True, help_text='Private notes/rubric guidance for evaluators.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.program')),
            ],
            options={
                'ordering': ['program', 'skill', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcceptableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptable_answers', to='question_bank.question')),
            ],
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stimulus_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('text_audio', 'Text + Audio'), ('scenario', 'Scenario')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Reading passage, notice, scenario, transcript, etc.')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='question_bank/audio/')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='question_bank/images/')),
                ('transcript', models.TextField(blank=True, help_text='Optional audio transcript for administration/grading. Not automatically shown to students.')),
                ('source_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimuli', to='assessments.program')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='stimulus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_bank.stimulus'),
        ),
        migrations.CreateModel(
            name='PartQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('points_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_assignments', to='assessments.testpart')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_assignments', to='question_bank.question')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('part', 'question'), name='unique_question_per_part'), models.UniqueConstraint(fields=('part', 'order'), name='unique_question_order_per_part')],
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_position', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='question_bank.question')),
            ],
            options={
                'ordering': ['correct_position'],
                'constraints': [models.UniqueConstraint(fields=('question', 'correct_position'), name='unique_ordering_position_per_question')],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.question')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('question', 'order'), name='unique_option_order_per_question')],
            },
        ),
    ]
