# Generated by Django 5.2.17 on 2026-08-21 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Optional total expected test duration.', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mock_tests', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='assessments.program')),
            ],
            options={
                'ordering': ['program', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('interview', 'Interview')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Optional section timer in seconds.', null=True)),
                ('can_pause', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.mocktest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('prompt_mode', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('text_audio', 'Text + Audio')], default='text', max_length=20)),
                ('question_visible', models.BooleanField(default=True, help_text='Turn off when the candidate should hear but not see the question.')),
                ('preparation_seconds', models.PositiveIntegerField(default=0)),
                ('response_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('question_count', models.PositiveIntegerField(blank=True, null=True)),
                ('max_audio_plays', models.PositiveIntegerField(blank=True, help_text='Leave empty when no specific playback restriction is required.', null=True)),
                ('recording_required', models.BooleanField(default=False)),
                ('min_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='assessments.testsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='testsection',
            constraint=models.UniqueConstraint(fields=('mock_test', 'order'), name='unique_section_order_per_test'),
        ),
        migrations.AddConstraint(
            model_name='testpart',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_part_order_per_section'),
        ),
    ]
