# Generated by Django 5.2.17 on 2026-08-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='minimum_response_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Optional minimum response duration when the source specifies a minimum rather than a fixed timer.', null=True),
        ),
    ]
