# Generated by Django 5.2.17 on 2026-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='Name exactly as the student wants it to appear on a future certificate.', max_length=160),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_language',
            field=models.CharField(choices=[('english', 'English'), ('nepali', 'Nepali')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Student profile photo. This can later be reused for certificate generation.', null=True, upload_to='profiles/photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='result_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
