# Generated by Django 5.2.17 on 2026-08-23 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_testpart_minimum_response_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/%Y/%m/')),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='assessments.program')),
            ],
            options={
                'ordering': ['program__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('general', 'General'), ('speaking', 'Speaking'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing')], default='general', max_length=20)),
                ('material_type', models.CharField(choices=[('text', 'Text lesson'), ('document', 'Document / PDF'), ('audio', 'Audio lesson'), ('video_link', 'Video link'), ('download', 'Downloadable file')], default='text', max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'csv', 'txt', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='courses/audio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'ogg', 'webm'])])),
                ('external_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_course_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TestMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('instructions', models.TextField(blank=True)),
                ('passage_text', models.TextField(blank=True, help_text='Reading passage or supporting text.')),
                ('prompt_text', models.TextField(blank=True, help_text='Writing prompt or question text.')),
                ('transcript', models.TextField(blank=True, help_text='Optional Listening transcript.')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='test_materials/audio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'ogg', 'webm'])])),
                ('attachment', models.FileField(blank=True, null=True, upload_to='test_materials/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'csv', 'txt', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('answer_key', models.JSONField(blank=True, default=dict, help_text='Optional structured answer key.')),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('is_question_bank_ready', models.BooleanField(default=False, help_text='Mark when the material has been reviewed and is ready to be converted into question-bank items.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_materials', to='academy.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_materials', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_test_materials', to='assessments.program')),
            ],
            options={
                'ordering': ['program', 'skill', '-created_at'],
            },
        ),
    ]
